def random_id(Len):
    import string
    import random
    s = string.ascii_letters
    s = list(s)
    ch1 = random.choice(s)
    ch2 = random.choice(s)
    ch3 = random.choice(s)
    ch4 = random.choice(s)
    ch5 = random.choice(s)
    ch6 = random.choice(s)
    ch7 = random.choice(s)
    ch8 = random.choice(s)
    ch9 = random.choice(s)
    ch10 = random.choice(s)
    ch11 = random.choice(s)
    ch12 = random.choice(s)
    ch13 = random.choice(s)
    ch14 = random.choice(s)
    ch15 = random.choice(s)
    ch16 = random.choice(s)
    ch17 = random.choice(s)
    ch18 = random.choice(s)
    ch19 = random.choice(s)
    ch20 = random.choice(s)
    ch21 = random.choice(s)
    ch22 = random.choice(s)
    ch23 = random.choice(s)
    ch24 = random.choice(s)
    ch25 = random.choice(s)
    ch26 = random.choice(s)
    ch27 = random.choice(s)
    ch28 = random.choice(s)
    ch29 = random.choice(s)
    ch30 = random.choice(s)
    ch31 = random.choice(s)
    ch32 = random.choice(s)
    ch33 = random.choice(s)
    ch34 = random.choice(s)
    ch35 = random.choice(s)
    ch36 = random.choice(s)
    ch37 = random.choice(s)
    ch38 = random.choice(s)
    ch39 = random.choice(s)
    ch40 = random.choice(s)
    ch41 = random.choice(s)
    ch42 = random.choice(s)
    ch43 = random.choice(s)
    ch44 = random.choice(s)
    ch45 = random.choice(s)
    ch46 = random.choice(s)
    ch47 = random.choice(s)
    ch48 = random.choice(s)
    ch49 = random.choice(s)
    ch50 = random.choice(s)
    randomid = f"{ch1}{ch2}{ch3}{ch4}{ch5}{ch6}{ch7}{ch8}{ch9}{ch10}{ch11}{ch12}{ch13}{ch14}{ch15}{ch16}{ch17}{ch18}{ch19}{ch20}{ch21}{ch22}{ch23}{ch24}{ch25}{ch26}{ch27}{ch28}{ch29}{ch30}{ch31}{ch32}{ch33}{ch34}{ch35}{ch36}{ch37}{ch38}{ch39}{ch40}{ch41}{ch42}{ch43}{ch44}{ch45}{ch46}{ch47}{ch48}{ch49}{ch50}"
    randomidlen = randomid[0:Len]
    print(randomidlen)


